# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Yash Kachave"
subtitle: "See the world through my eyes!"
author: "Yash Kachave"
header:
 title: "Wallpapers and Photographs"
 subtitle: "by Yash Kachave"
footer:
 name: "Hey there, my name is Yash"
 bio: "I am a designer and a tech aficionado from India. I Love making wallpapers and captuing Photographs."
 github: "Github <a href=\"https://github.com/Introdructor\">Follow Me</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/rampatra"
